In [24]:
import pandas as pd
df = pd.read_csv("source/wine.txt")
df.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,label
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [25]:
dataset_stage = df.sample(n=len(df), replace=True, random_state=0)
dataset_stage.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,label
172,14.16,2.51,2.48,20.0,91,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660,3
47,13.90,1.68,2.12,16.0,101,3.10,3.39,0.21,2.14,6.10,0.91,3.33,985,1
117,12.42,1.61,2.19,22.5,108,2.00,2.09,0.34,1.61,2.06,1.06,2.96,345,2
67,12.37,1.17,1.92,19.6,78,2.11,2.00,0.27,1.04,4.68,1.12,3.48,510,2
103,11.82,1.72,1.88,19.5,86,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415,2

In [26]:
index = dataset_stage.index

In [27]:
dataset_recovery = df.loc[index]
dataset_recovery.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,label
172,14.16,2.51,2.48,20.0,91,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660,3
47,13.90,1.68,2.12,16.0,101,3.10,3.39,0.21,2.14,6.10,0.91,3.33,985,1
117,12.42,1.61,2.19,22.5,108,2.00,2.09,0.34,1.61,2.06,1.06,2.96,345,2
67,12.37,1.17,1.92,19.6,78,2.11,2.00,0.27,1.04,4.68,1.12,3.48,510,2
103,11.82,1.72,1.88,19.5,86,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415,2

In [28]:
oob_indexes = [data_index for data_index in range(len(df)) if data_index not in index.values]

In [31]:
print(len(oob_indexes), len(index.values), len(df))

62 178 178

In [32]:
print(len(set(index.values)))

116

In [35]:
print(index.values)

[172  47 117  67 103   9  21  36  87  70  88 140  58  39  87 174  88  81
 165  25  77  72   9 148 115  79 175  82  99 177  29 147 147 142 167  32
   9 127  32  31 151 163 114  28  34 128 128 164  53 133  38  17  79 132
 105  42  31 120   1  65 169  57  35 102 119  11 174  82  91 128 142  99
  53 140 121 170  84  68   6  47 127 131 100  78 143 148  23 141 117  85
  48  49  69 169 163  95  94   0 113  36 162  48  93 131  98  42 112 149
 127   0 138 114  43 127  23 130 121  98  62 163 123  82 174 148  50 155
  14  41  58  36  10  86  43 104  11   2  51  80  32 128  38  19 174  42
 115  77  30  24 125   2   3  94 107  13 112  40  72  19  95  72 154  67
  61  14  96   4 139  86 121 109  75  16 152 157 149 110  25 121]

In [33]:
dataset_recovery = dataset_recovery.reset_index(drop=True)
dataset_recovery.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,label
0,14.16,2.51,2.48,20.0,91,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660,3
1,13.90,1.68,2.12,16.0,101,3.10,3.39,0.21,2.14,6.10,0.91,3.33,985,1
2,12.42,1.61,2.19,22.5,108,2.00,2.09,0.34,1.61,2.06,1.06,2.96,345,2
3,12.37,1.17,1.92,19.6,78,2.11,2.00,0.27,1.04,4.68,1.12,3.48,510,2
4,11.82,1.72,1.88,19.5,86,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415,2

In [39]:
test = df.loc[[1, 3, 6, 8]]
test.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,label
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
6,14.39,1.87,2.45,14.6,96,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290,1
8,14.83,1.64,2.17,14.0,97,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045,1

In [40]:
for ind, data in test.iterrows():
    print(f'ind={ind}, data={data}')

ind=1, data=Alcohol                           13.20
Malic acid                         1.78
Ash                                2.14
Alcalinity of ash                 11.20
Magnesium                        100.00
Total phenols                      2.65
Flavanoids                         2.76
Nonflavanoid phenols               0.26
Proanthocyanins                    1.28
Color intensity                    4.38
Hue                                1.05
OD280/OD315 of diluted wines       3.40
Proline                         1050.00
label                              1.00
Name: 1, dtype: float64
ind=3, data=Alcohol                           14.37
Malic acid                         1.95
Ash                                2.50
Alcalinity of ash                 16.80
Magnesium                        113.00
Total phenols                      3.85
Flavanoids                         3.49
Nonflavanoid phenols               0.24
Proanthocyanins                    2.18
Color intensity                    7.80
Hue                                0.86
OD280/OD315 of diluted wines       3.45
Proline                         1480.00
label                              1.00
Name: 3, dtype: float64
ind=6, data=Alcohol                           14.39
Malic acid                         1.87
Ash                                2.45
Alcalinity of ash                 14.60
Magnesium                         96.00
Total phenols                      2.50
Flavanoids                         2.52
Nonflavanoid phenols               0.30
Proanthocyanins                    1.98
Color intensity                    5.25
Hue                                1.02
OD280/OD315 of diluted wines       3.58
Proline                         1290.00
label                              1.00
Name: 6, dtype: float64
ind=8, data=Alcohol                           14.83
Malic acid                         1.64
Ash                                2.17
Alcalinity of ash                 14.00
Magnesium                         97.00
Total phenols                      2.80
Flavanoids                         2.98
Nonflavanoid phenols               0.29
Proanthocyanins                    1.98
Color intensity                    5.20
Hue                                1.08
OD280/OD315 of diluted wines       2.85
Proline                         1045.00
label                              1.00
Name: 8, dtype: float64